[package]
name = "specs"
version = "0.1.0"
edition = "2024"

[dependencies]
stub-macro = "0.1.9"
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
quick-xml = { version = "0.38.4", features = ["serde", "serialize"] }
